### ISSUE TITLE
_modcfmlredirected

### ISSUE THREAD

**Issue by ivanionut** [viviotech/mod_cfml#24]
Hi,
I'm using the following stack: nginx 1.6.0 & tomcat9, lucee 5.3 and mod_cfml-valve_v1.1.09.jar

At the first access _(for example after restarting the server)_ I get this redirect:

`http://www.website.com/index.cfm?&_modcfmlredirected`

How can I avoid it?
thank you!

**Comment by utdream** [comment]
Hello,

The _modcfmlredirected value is a new feature of the latest release that helps prevent race conditions on some high-traffic sites.

@paulklinkenberg I wonder if we could track this internally somehow, so that it doesn't interfere with a user's URI? Something like a memory-based table of contexts that are currently being processed? If nothing else, we could potentially make this a configurable variable that can be set in the valve config in the server.xml file.

**Comment by paulklinkenberg** [comment]
Hi there! Yes, we could make this value anything we want. It _is_ a bit annoying that the redirect is even necessary, and then adding something to the url sucks even more. But I haven't figured out a better way, and it prevents actual situations where users previously had a 500 error returned.
The url value could be any string which is not often found at the end of a query string, e.g. 2 low-dashes "&__" or "&_redir" or whatever.

Then again, is this really an issue? Does it bother anyone? Or is it just us developers and nerds who think something of it?

**Comment by paulklinkenberg** [comment]
Turned out, the url parameter was not necessary in 99% of cases. I updated the code already, will do a PR in a day or so.
Doing another improvement as well, for the Apache module, which is not finished yet.

**Comment by utdream** [comment]
Nice. I like that you made the redirect string configurable. Thank you for your work on this Paul!
