### ISSUE TITLE
first POST request after startup results in a 302

### ISSUE THREAD

**Issue by zspitzer** [viviotech/mod_cfml#26]
a 302 on a POST doesn't preserve the form fields, so with modern javascript apps where the first request is a login will fail

https://dev.lucee.org/t/redirected-initial-request-after-start-is-handled-differently/4482
https://dev.lucee.org/t/first-call-after-restart-returns-302/491
https://luceeserver.atlassian.net/browse/LDEV-1988

https://github.com/viviotech/mod_cfml/blob/master/java/mod_cfml-valve/src/mod_cfml/core.java#L274

**Comment by utdream** [comment]
Looking into this, the actual 302 response code is coming from the Tomcat response method that mod_cfml uses after a new host is created:
https://tomcat.apache.org/tomcat-5.5-doc/catalina/docs/api/org/apache/catalina/connector/Response.html#sendRedirect(java.lang.String)

Further, it looks like we've been using this response since the initial release, so it's not like something has changed along the way.

As of Tomcat 8 it looks like, there's a new version of that method that allows us to customize a response code. However, that won't actually fix the issue your having.

Specifically, the problem lies with having to do the redirect at all. Redirects by their nature do not preserve form data, but instead prompt the browser to re-issue a request. The reason we have to do a redirect is because the first time the request goes through tomcat, mod_cfml is only called AFTER tomcat has already done the host resolution.

I wonder if there would be some way that we could proxy the first request into an entirely new request  so that tomcat would properly call that request - or something along those lines... I can see that solution creating many of it's own problems, so will need to do more research here.

**Comment by utdream** [comment]
I wonder if the solution to this might be on the client site. Not just for mod_cfml enabled sites, but for an API that responds with a 302? For example, in JS, you could post something to the affect of "if responseCode = 302, reissue request" (to paraphrase).

**Comment by zspitzer** [comment]
is this helpful? 
https://www.logicbig.com/tutorials/java-ee-tutorial/java-servlet/servlet-redirect.html

using a 307 response code https://tools.ietf.org/html/rfc7231#section-6.4.7 tells the browser to preserve the METHOD

> 6.4.7.  307 Temporary Redirect
> 
>    The 307 (Temporary Redirect) status code indicates that the target
>    resource resides temporarily under a different URI and the user agent
>    MUST NOT change the request method if it performs an automatic
>    redirection to that URI.  Since the redirection can change over time,
>    the client ought to continue using the original effective request URI
>    for future requests.
> 
>    The server SHOULD generate a Location header field in the response
>    containing a URI reference for the different URI.  The user agent MAY
>    use the Location field value for automatic redirection.  The server's
>    response payload usually contains a short hypertext note with a
>    hyperlink to the different URI(s).
> 
>       Note: This status code is similar to 302 (Found), except that it
>       does not allow changing the request method from POST to GET.  This
>       specification defines no equivalent counterpart for 301 (Moved
>       Permanently) ([RFC7238], however, defines the status code 308
>       (Permanent Redirect) for this purpose).

**Comment by zspitzer** [comment]
@utdream cool! 

![image](https://user-images.githubusercontent.com/426404/63763779-b3132680-c8c5-11e9-8d34-3f2ec0fa7a31.png)

the easiest way to test to to open the admin, restart lucee and try to login. with 1.11 it finally works first time :)

initialRedirectResponseCode might be a better name?

**Comment by zspitzer** [comment]
I'd be making this the default, just so it all works OOTB
