### ISSUE TITLE
First load of each application after server start restart appends index.cfm?

### ISSUE THREAD

**Issue by cfuj** [viviotech/mod_cfml#29]
After restarting the server, or after application has expired (from configured time-out), the first load appends `index.cfm` to the URLs ending in `/`, or `.cfm` to URLs such as `mysite.com/page`.

I updated mod_cfml from 1.04 to 1.09, and then 1.10 too, and this changed to append `index.cfm?` to the URL.

I'm on the latest version of Lucee, `5.3.3.62`, IIS 10, & Windows 10.

**Comment by utdream** [comment]
Hi there,

I think I just responded to this on stack overflow. Since this isn't really a bug per-se (index.cfm IS your default document after all), let's talk about it there. For anyone who wants to follow along, here's the link:

https://stackoverflow.com/questions/58044430/lucee-on-windows-appending-index-cfm-on-first-request-to-application/58066591#58066591

On a separate note, there ARE ways to configure Lucee to handle different file extensions. Using those methods, you could have Lucee process .php extensions and really confuse attackers, or just create your own extensions that you want Lucee to process. I'd recommend talking about that on dev.lucee.org.
