### ISSUE TITLE
Injecting config into the <Context>

### ISSUE THREAD

**Issue by sbleon** [viviotech/mod_cfml#33]
I'm considering using an alternate Session Manager (e.g. https://github.com/magro/memcached-session-manager) for external storage of sessions and session replication. In order to do so, I have to create a `<Manager>` created inside the`<Context>` element. This currently isn't possible with mod_cfml, because it generates the `<Context>` and doesn't seem to have an injection feature.

1. Is there a way to inject config into `<Context>` that I'm missing?
2. How would you feel about a PR that adds this feature?

**Comment by utdream** [comment]
Hi Leon,

If you need to customize your context you can already do that "the old-fashioned way" by adding the context config to your Tomcat config. The only difference between a context that you add manually and a context that mod_cfml adds is when they're loaded. Manual contexts are loaded at Tomcat boot and mod_cfml configs are created/loaded on first hit. Other than that they're functionally identical.

You can add your config manually by editing your Tomcat server.xml file. Comments are there at the bottom of the file to show you how.

Since you can already do this easily with a simple, single file edit, I doesn't make sense to change mod_cfml. Appreciate where you're minds at though. Keep the ideas coming! =)

-Jordan

**Comment by zspitzer** [comment]
I think this is a really good idea, having more control over configuration is always nice

**Comment by sbleon** [comment]
Thanks for the positive feedback, Zac!

I'm actually dropping the idea of using a Tomcat session manager, after
doing some local tests, because we have too much stuff in our sessions that
Tomcat can't possibly serialize/deserialize. So I'm not going to pursue
this issue further.

**Comment by sbleon** [comment]
And thanks for your thoughts on the matter, Jordan. I appreciate the speedy response!
